CC = g++
LIBS = liostream

Main: Main.o HarmonicSeries.o
	$(CC) Main.o HarmonicSeries.o -o Main
Main.o: Main.cpp
	$(CC) Main.cpp -c

HarmonicSeries.o: HarmonicSeries.cpp
	$(CC) HarmonicSeries.cpp -c

